
title: 'test title'
baseurl: "/"
url: "https://of0xb1t.github.io"

header_pages:
  - index.md
#  - about.md
  - contact.md

style: dark

footer: '"Success comes from curiosity, concentration, perseverance and self-criticism." A.E.'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console

plugins:
 - jekyll-seo-tag
